### ISSUE TITLE
Stylize the input box for different states

### ISSUE THREAD

**Issue by hemchander23** [freshhuddle/fw-input#1]
You can make the CSS changes at https://github.com/freshhuddle/fw-input/blob/master/src/components/fw-input/fw-input.css

![image](https://user-images.githubusercontent.com/19341550/66147393-62ad8800-e62c-11e9-8df6-e250e54160a0.png)

Color Palette for your reference

![image](https://user-images.githubusercontent.com/19341550/66147657-e2d3ed80-e62c-11e9-90a6-b5645f54eeb9.png)

**Comment by aachh** [comment]
sent pull request 😉

**Comment by hemchander23** [comment]
Thanks, @aachh. Added review comments. Just minor ones before the merge 🎉

**Comment by hemchander23** [comment]
Fixes #2 Thanks!
